version = 1

test_patterns = ["scripts/test/**"]

exclude_patterns = [
  "eslint.config.js",
  "src/gadgets/libBottomRightCorner/**",
  "src/gadgets/libCachedCode/**",
  "src/gadgets/libDiscussionUtil/**",
  "src/gadgets/libHashwasm/**",
  "src/gadgets/libJQuery/**",
  "src/gadgets/libJSON5/**",
  "src/gadgets/libOOUIDialog/**",
  "src/gadgets/libPolyfill/**",
  "src/gadgets/libUtil/**",
  "src/gadgets/libip/**",
  "src/gadgets/prism/**",
  "src/gadgets/prism-core/**",
  "src/gadgets/prism-language-bash/**",
  "src/gadgets/prism-language-c/**",
  "src/gadgets/prism-language-clike/**",
  "src/gadgets/prism-language-coffeescript/**",
  "src/gadgets/prism-language-cpp/**",
  "src/gadgets/prism-language-csharp/**",
  "src/gadgets/prism-language-css/**",
  "src/gadgets/prism-language-java/**",
  "src/gadgets/prism-language-javascript/**",
  "src/gadgets/prism-language-json/**",
  "src/gadgets/prism-language-latex/**",
  "src/gadgets/prism-language-lua/**",
  "src/gadgets/prism-language-markup/**",
  "src/gadgets/prism-language-perl/**",
  "src/gadgets/prism-language-php/**",
  "src/gadgets/prism-language-python/**",
  "src/gadgets/prism-language-regex/**",
  "src/gadgets/prism-language-ruby/**",
  "src/gadgets/prism-language-typescript/**",
  "src/gadgets/prism-language-wiki/**",
  "src/gadgets/prism-language-yaml/**",
  "src/gadgets/prism-plugin-javadoclike/**",
  "src/gadgets/prism-plugin-jsdoc/**",
  "src/gadgets/prism-plugin-match-braces/**",
  "src/gadgets/prism-plugin-phpdoc/**",
  "src/gadgets/prism-plugin-previewers/**",
  "src/gadgets/HotCat/**",
  "src/gadgets/Navigation_popups/**",
  "src/gadgets/localforage/**",
  "src/gadgets/code-prettify/**",
  "src/gadgets/SpecialWikitext/**",
  "src/gadgets/FlowThreadCheck/**"
]

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = [
    "browser",
    "jquery"
  ]